
disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - void_return
 - trailing_comma
opt_in_rules: # some rules are only opt-in

included:

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

line_length: 180

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 700
  error: 1500

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
variable_name:
min_length:
    warning: 2
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
